##########################################################################
# 部署配置文件(base)
# 本配置文件(xx.yml)中的变量(${xxx})是从同级目录下的.env文件中读取的
##########################################################################
# compose支持的版本2
version: "2"
services:
  # http
  http:
    image: "${IMAGE_HTTP}"
    container_name: "http.${PRODUCT_NAME}.${COMPANY_NAME}"
    hostname: "http.${PRODUCT_NAME}.${COMPANY_NAME}"
    restart: "always"
    env_file:
      - ./nginx.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/http/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volume/http/conf/server.conf:/etc/nginx/conf.d/default.conf:ro
      - ./volume/share/data:/usr/share/nginx/html:ro
    network_mode: "host"
    extra_hosts:
      - "http.${PRODUCT_NAME}.${COMPANY_NAME}:${HOST_IP}"
  # ftp
  ftp:
    image: "${IMAGE_FTP}"
    container_name: "ftp.${PRODUCT_NAME}.${COMPANY_NAME}"
    hostname: "ftp.${PRODUCT_NAME}.${COMPANY_NAME}"
    restart: "always"
    env_file:
      - ./pureftpd.env
    environment:
      - PUBLICHOST=${HOST_IP}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/ftp/passwd:/etc/pure-ftpd/passwd:rw
      - ./volume/ftp/ssl:/etc/ssl/private/:rw
      - ./volume/ftp/logs:/var/log/pure-ftpd/:rw
      - ./volume/share/data:/home/ftpusers/szgd/:rw
    network_mode: "host"
    extra_hosts:
      - "ftp.${PRODUCT_NAME}.${COMPANY_NAME}:${HOST_IP}"
    # create an ftp user: e.g. bob with chroot access only to /home/ftpusers/bob
    # pure-pw useradd bob -f /etc/pure-ftpd/passwd/pureftpd.passwd -m -u ftpuser -d /home/ftpusers/bob
